/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package karnkha;

/**
 *
 * @author Supawach
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background2 = new javax.swing.JPanel();
        iconshoppingcart = new javax.swing.JLabel();
        iconmoney = new javax.swing.JLabel();
        iconfix = new javax.swing.JLabel();
        iconlogistic = new javax.swing.JLabel();
        iconreport = new javax.swing.JLabel();
        iconproduct = new javax.swing.JLabel();
        iconreceiveproducts = new javax.swing.JLabel();
        iconresume = new javax.swing.JLabel();
        icondealer = new javax.swing.JLabel();
        iconanalytics = new javax.swing.JLabel();
        background1 = new javax.swing.JPanel();
        sittichaikarnkha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background2.setBackground(new java.awt.Color(255, 255, 255));
        background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconshoppingcart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-cart 1.png"))); // NOI18N
        background2.add(iconshoppingcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 106, -1, -1));

        iconmoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/money 1.png"))); // NOI18N
        background2.add(iconmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 106, -1, -1));

        iconfix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fix 1.png"))); // NOI18N
        background2.add(iconfix, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 98, -1, -1));

        iconlogistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logistic 2.png"))); // NOI18N
        background2.add(iconlogistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 98, -1, -1));

        iconreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report 1.png"))); // NOI18N
        background2.add(iconreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1619, 98, -1, -1));

        iconproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product 1.png"))); // NOI18N
        background2.add(iconproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 485, -1, -1));

        iconreceiveproducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1000005428 1.png"))); // NOI18N
        background2.add(iconreceiveproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 485, -1, -1));

        iconresume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resume 1.png"))); // NOI18N
        background2.add(iconresume, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 477, -1, -1));

        icondealer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/team 1.png"))); // NOI18N
        background2.add(icondealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 477, -1, -1));

        iconanalytics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analytics 1.png"))); // NOI18N
        background2.add(iconanalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(1619, 477, -1, -1));

        background1.setBackground(new java.awt.Color(147, 26, 37));

        sittichaikarnkha.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        sittichaikarnkha.setText("SITTICHAI KARNKHA");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(718, 718, 718)
                .addComponent(sittichaikarnkha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(sittichaikarnkha)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(background2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JLabel iconanalytics;
    private javax.swing.JLabel icondealer;
    private javax.swing.JLabel iconfix;
    private javax.swing.JLabel iconlogistic;
    private javax.swing.JLabel iconmoney;
    private javax.swing.JLabel iconproduct;
    private javax.swing.JLabel iconreceiveproducts;
    private javax.swing.JLabel iconreport;
    private javax.swing.JLabel iconresume;
    private javax.swing.JLabel iconshoppingcart;
    private javax.swing.JLabel sittichaikarnkha;
    // End of variables declaration//GEN-END:variables
}
