/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Com_Table;

import karnkha.Main;
import Com_Table.Table_OrderRec;
import component.Order_Received;

/**
 *
 * @author pongs
 */
public class Table_RecivePro extends javax.swing.JPanel {

    /**
     * Creates new form Table_OrderRec
     */
    public Table_RecivePro() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Information = new javax.swing.JTextArea();
        Label_Note = new javax.swing.JLabel();
        ScrollPane_Note = new javax.swing.JScrollPane();
        Table_Order_Record1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        back_button1 = new javax.swing.JLabel();
        All_prices = new javax.swing.JLabel();
        Label_Aprices1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(580, 800));
        setPreferredSize(new java.awt.Dimension(590, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jTextArea_Information.setEditable(false);
        jTextArea_Information.setColumns(20);
        jTextArea_Information.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea_Information.setLineWrap(true);
        jTextArea_Information.setRows(5);
        jScrollPane4.setViewportView(jTextArea_Information);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, 360, 80));

        Label_Note.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Note.setText("หมายเหตุ :");
        add(Label_Note, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, -1, -1));

        Table_Order_Record1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Product", "Product Type", "Quantity", "Cost", "All Prices"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Order_Record1.getTableHeader().setReorderingAllowed(false);
        Table_Order_Record1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_Order_Record1MouseClicked(evt);
            }
        });
        ScrollPane_Note.setViewportView(Table_Order_Record1);

        add(ScrollPane_Note, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 570, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_button1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        back_button1.setForeground(new java.awt.Color(139, 139, 139));
        back_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-button Table.png"))); // NOI18N
        back_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button1MouseClicked(evt);
            }
        });
        jPanel1.add(back_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        All_prices.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        All_prices.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        All_prices.setText("00.00");
        jPanel1.add(All_prices, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 120, -1));

        Label_Aprices1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Aprices1.setText("ราคาสินค้าทั้งหมด :");
        jPanel1.add(Label_Aprices1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void Table_Order_Record1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_Order_Record1MouseClicked

    }//GEN-LAST:event_Table_Order_Record1MouseClicked

    private void back_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MouseClicked
        Order_Received.body.removeAll();
        Order_Received.body.add(new Table_OrderRec());
        Order_Received.body.repaint();
        Order_Received.body.revalidate();
    }//GEN-LAST:event_back_button1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel All_prices;
    private javax.swing.JLabel Label_Aprices1;
    private javax.swing.JLabel Label_Note;
    private javax.swing.JScrollPane ScrollPane_Note;
    private javax.swing.JTable Table_Order_Record1;
    private javax.swing.JLabel back_button1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_Information;
    // End of variables declaration//GEN-END:variables
}
