/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Com_Table;

import component.Order_Received;
import javax.swing.JOptionPane;

/**
 *
 * @author pongs
 */
public class Table_OrderRec extends javax.swing.JPanel {

    /**
     * Creates new form Table_OrderRec
     */
    public Table_OrderRec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Order_Record1 = new javax.swing.JTable();
        Date_label1 = new javax.swing.JLabel();
        Date_Text = new javax.swing.JLabel();
        Company_label = new javax.swing.JLabel();
        Date_Text1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(580, 800));
        setPreferredSize(new java.awt.Dimension(590, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Order_Record1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Company", "Quantity", "All Prices"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Order_Record1.getTableHeader().setReorderingAllowed(false);
        Table_Order_Record1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_Order_Record1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_Order_Record1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 570, 710));

        Date_label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date_label1.setText("วันที่ : ");
        add(Date_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Date_Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date_Text.setText("DD/MM/YY");
        add(Date_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        Company_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Company_label.setText("บริษัท : ");
        add(Company_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        Date_Text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date_Text1.setText("ชื่อบริษัท");
        add(Date_Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void Table_Order_Record1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_Order_Record1MouseClicked
        int index = Table_Order_Record1.getSelectedRow();
            Order_Received.body.removeAll();
            Order_Received.body.add(new Table_RecivePro());
            Order_Received.body.repaint();
            Order_Received.body.revalidate();
            JOptionPane.showMessageDialog(this, "คุณคลิกที่แถวที่ " + index);
    }//GEN-LAST:event_Table_Order_Record1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Company_label;
    private javax.swing.JLabel Date_Text;
    private javax.swing.JLabel Date_Text1;
    private javax.swing.JLabel Date_label1;
    private javax.swing.JTable Table_Order_Record1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
