/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author aess2
 */
public class loginfrom extends javax.swing.JPanel {

    /**
     * Creates new form loginfrom
     */
    public loginfrom() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        eye_hide = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        T_User1 = new javax.swing.JTextField();
        BLogin = new javax.swing.JButton();
        P_Pass1 = new javax.swing.JPasswordField();

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, 50));

        eye_hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye_hide.png"))); // NOI18N
        eye_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye_hideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eye_hideMouseReleased(evt);
            }
        });
        Login.add(eye_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 30, 40));

        eye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye.png"))); // NOI18N
        Login.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 30, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Password");
        Login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 230, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("User Name");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 230, 40));

        T_User1.setForeground(new java.awt.Color(153, 153, 153));
        T_User1.setText("User Name");
        T_User1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_User1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T_User1FocusLost(evt);
            }
        });
        Login.add(T_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 280, 40));

        BLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BLogin.setText("Login");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        Login.add(BLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 280, 30));

        P_Pass1.setForeground(new java.awt.Color(153, 153, 153));
        Login.add(P_Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void T_User1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_User1FocusGained
        if(T_User1.getText().equals("User Name"))
       {
           T_User1.setText("");
           T_User1.setForeground(new Color(0, 0, 0));
       }
    }//GEN-LAST:event_T_User1FocusGained

    private void T_User1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_User1FocusLost
        if (T_User1.getText().length()==0) {
            T_User1.setText("User Name");
            T_User1.setForeground(new Color(123, 123, 123));
        }
    }//GEN-LAST:event_T_User1FocusLost

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BLoginActionPerformed

    private void eye_hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_hideMousePressed
       eye.setVisible(true);
       eye_hide.setVisible(false);
       P_Pass1.setEchoChar((char)0);
    }//GEN-LAST:event_eye_hideMousePressed

    private void eye_hideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_hideMouseReleased
        eye.setVisible(false);
        eye_hide.setVisible(true);
        P_Pass1.setEchoChar('*');
    }//GEN-LAST:event_eye_hideMouseReleased

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogin;
    private javax.swing.JPanel Login;
    private javax.swing.JPasswordField P_Pass1;
    private javax.swing.JTextField T_User1;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel eye_hide;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
